version: 2
project_name: xdsrun

before:
  hooks:
    - go mod tidy

builds:
  -
    id: xdsrun
    main: .
    binary: xdsrun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - mipsle
      - riscv64
      - loong64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.buildTime={{.Date}}

archives:
  - 
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md
    
checksum:
  name_template: 'checksums.txt'

upx:
  -
    enabled: true
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

# snapshot:
#   name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: NanCunChild
    name: xdsrun-login
  draft: false
  prerelease: auto