version: 2
project_name: xdsrun

before:
  hooks:
    - go mod tidy

builds:
  -
    id: xdsrun
    main: .
    binary: xdsrun
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.buildTime={{.Date}}
    
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - linux_mipsle
      - linux_riscv64
      - linux_loong64
      - linux_ppc64le

      - windows_386
      - windows_amd64
      - windows_arm64

      - darwin_amd64       # Intel Mac
      - darwin_arm64       # M Mac

      - android_arm64
      - android_arm_7

      - freebsd_amd64
      - freebsd_arm64

archives:
  - 
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md
    
checksum:
  name_template: 'checksums.txt'

upx:
  -
    enabled: true
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

# snapshot:
#   name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: NanCunChild
    name: xdsrun
  draft: false
  prerelease: auto